{
	"type":"Scene",
	"props":{
		"name":"Hero_03",
		"enableFog":false,
		"fogStart":0,
		"fogRange":300
	},
	"customProps":{
		"skyBox":{},
		"lightmaps":[],
		"ambientColor":[
			0.212,
			0.227,
			0.259
		],
		"fogColor":[
			0.5,
			0.5,
			0.5
		]
	},
	"child":[
		{
			"type":"Sprite3D",
			"props":{
				"isStatic":false,
				"name":"Hero_03"
			},
			"customProps":{
				"layer":9,
				"translate":[
					4.83,
					-0.06,
					0
				],
				"rotation":[
					0,
					0,
					0,
					-1
				],
				"scale":[
					1,
					1,
					1
				]
			},
			"components":{
				"BoxCollider":{
					"isTrigger":false,
					"center":[
						0,
						1.11599,
						0
					],
					"size":[
						1,
						2.226691,
						1
					]
				},
				"Rigidbody":{}
			},
			"child":[
				{
					"type":"Sprite3D",
					"props":{
						"isStatic":false,
						"name":"Offset"
					},
					"customProps":{
						"layer":0,
						"translate":[
							0,
							0,
							0
						],
						"rotation":[
							0,
							0,
							0,
							-1
						],
						"scale":[
							1,
							1,
							1
						]
					},
					"components":{},
					"child":[
						{
							"type":"Sprite3D",
							"props":{
								"isStatic":false,
								"name":"hero03_action"
							},
							"customProps":{
								"layer":0,
								"translate":[
									0,
									0,
									0
								],
								"rotation":[
									0,
									0,
									0,
									-1
								],
								"scale":[
									1,
									1,
									1
								]
							},
							"components":{
								"Animator":{
									"avatar":{
										"path":"Assets/1001/Art/Models/Hero/hero03/hero03_action-hero03_action-hero03_actionAvatar.lav",
										"linkSprites":{
											"Bone006":[
												"Bone006"
											],
											"Bip001 Spine1":[
												"Bip001 Spine1"
											],
											"jingubang":[
												"jingubang"
											]
										}
									},
									"clipPaths":[
										"Assets/1001/Art/Models/Hero/hero01/hero01_admin01-hero_run.lani",
										"Assets/1001/Art/Models/Hero/hero01/hero01_admin01-hero_run_left.lani",
										"Assets/1001/Art/Models/Hero/hero01/hero01_admin01-hero_run_right.lani",
										"Assets/1001/Art/Models/Hero/hero01/hero01_admin01-hero_shovel.lani",
										"Assets/1001/Art/Models/Hero/hero01/hero01_admin01-hero_jump.lani",
										"Assets/1001/Art/Models/Hero/hero01/hero01_admin01-hero_jump_setdown.lani",
										"Assets/1001/Art/Models/Hero/hero01/hero01_admin01-hero_down.lani",
										"Assets/1001/Art/Models/Hero/hero01/hero01_admin01-hero_stagger_l.lani",
										"Assets/1001/Art/Models/Hero/hero01/hero01_admin01-hero_stagger_r.lani",
										"Assets/1001/Art/Models/Hero/hero01/hero01_admin01-hero_lost1_01.lani",
										"Assets/1001/Art/Models/Hero/hero01/hero01_admin01-hero_jump_hello.lani",
										"Assets/1001/Art/Models/Hero/hero01/hero01_admin01-hero_jump_roll1.lani",
										"Assets/1001/Art/Models/Hero/hero01/hero01_admin01-hero_jump_roll2.lani",
										"Assets/1001/Art/Models/Hero/hero01/hero01_admin01-hero_jump_left.lani",
										"Assets/1001/Art/Models/Hero/hero01/hero01_admin01-hero_jump_right.lani",
										"Assets/1001/Art/Models/Hero/hero01/hero01_admin01-hero_flay.lani",
										"Assets/1001/Art/Models/Hero/hero01/hero01_admin01-hero_flay_fall.lani",
										"Assets/1001/Art/Models/Hero/hero01/hero01_admin02-hero_skate_down.lani",
										"Assets/1001/Art/Models/Hero/hero01/hero01_admin02-hero_skate_jump.lani",
										"Assets/1001/Art/Models/Hero/hero01/hero01_admin02-hero_skate_jump01.lani",
										"Assets/1001/Art/Models/Hero/hero01/hero01_admin02-hero_skate_jump02.lani",
										"Assets/1001/Art/Models/Hero/hero01/hero01_admin02-hero_skate_jump03.lani",
										"Assets/1001/Art/Models/Hero/hero01/hero01_admin02-hero_skate_left.lani",
										"Assets/1001/Art/Models/Hero/hero01/hero01_admin02-hero_skate_right.lani",
										"Assets/1001/Art/Models/Hero/hero01/hero01_admin02-hero_skate_run.lani",
										"Assets/1001/Art/Models/Hero/hero01/hero01_admin02-hero_skate_setdown.lani",
										"Assets/1001/Art/Models/Hero/hero01/hero01_admin02-hero_skate_shovel.lani",
										"Assets/1001/Art/Models/Hero/hero01/hero01_admin02-hero_skate_skidding.lani",
										"Assets/1001/Art/Models/Hero/hero01/hero01_admin02-hero_skate_jump04.lani",
										"Assets/1001/Art/Models/Hero/hero01/hero01_admin02-hero_skate_up_skb.lani",
										"Assets/1001/Art/Models/Hero/hero01/hero01_admin02-hero_skate_jump05.lani",
										"Assets/1001/Art/Models/Hero/hero01/hero01_admin01-hero_huaxiang.lani"
									],
									"playOnWake":true
								}
							},
							"child":[
								{
									"type":"Sprite3D",
									"props":{
										"isStatic":false,
										"name":"Bone006"
									},
									"customProps":{
										"layer":0,
										"translate":[
											0.004714012,
											-0.02409906,
											0.1026578
										],
										"rotation":[
											0.009306129,
											9.65595E-05,
											0.01038966,
											-0.9999027
										],
										"scale":[
											1.000001,
											1,
											1
										]
									},
									"components":{},
									"child":[
										{
											"type":"MeshSprite3D",
											"props":{
												"isStatic":false,
												"name":"huaban"
											},
											"customProps":{
												"layer":0,
												"translate":[
													0.06670477,
													-0.3999256,
													-0.09138215
												],
												"rotation":[
													-0.00929907,
													-0.0001932085,
													2.086163E-07,
													-0.9999568
												],
												"scale":[
													0.1,
													0.1000001,
													0.1
												],
												"meshPath":"Assets/1001/Art/Models/Hero/huaban/huaban-huaban.lm",
												"materials":[
													{
														"type":"Laya.BlinnPhongMaterial",
														"path":"Assets/1001/Art/Models/Hero/huaban/Materials/huaban.lmat"
													}
												]
											},
											"components":{},
											"child":[]
										}
									]
								},
								{
									"type":"Sprite3D",
									"props":{
										"isStatic":false,
										"name":"Bip001 Spine1"
									},
									"customProps":{
										"layer":0,
										"translate":[
											4.768372E-07,
											1.325784,
											-0.02664769
										],
										"rotation":[
											-0.5118297,
											-0.4878828,
											-0.5118297,
											-0.4878843
										],
										"scale":[
											1,
											1,
											1
										]
									},
									"components":{},
									"child":[
										{
											"type":"MeshSprite3D",
											"props":{
												"isStatic":false,
												"name":"BonePoint"
											},
											"customProps":{
												"layer":0,
												"translate":[
													0.177,
													-0.407,
													0
												],
												"rotation":[
													0,
													0,
													0,
													-1
												],
												"scale":[
													0.65,
													0.65,
													0.65
												],
												"meshPath":"Assets/1001/Art/Models/LayaPlane/Plane-Plane.lm",
												"materials":[
													{
														"type":"Laya.BlinnPhongMaterial",
														"path":"Assets/1001/Art/Models/Hero/hero03/Materials/hero_dt03.lmat"
													}
												]
											},
											"components":{
												"BoxCollider":{
													"isTrigger":false,
													"center":[
														0,
														0,
														0
													],
													"size":[
														1,
														1,
														1
													]
												}
											},
											"child":[]
										}
									]
								},
								{
									"type":"Sprite3D",
									"props":{
										"isStatic":false,
										"name":"jingubang"
									},
									"customProps":{
										"layer":0,
										"translate":[
											-0.6340475,
											1.004703,
											0.1967432
										],
										"rotation":[
											-0.5532265,
											0.564322,
											0.4476489,
											0.4184393
										],
										"scale":[
											1.000001,
											1,
											1
										]
									},
									"components":{},
									"child":[
										{
											"type":"MeshSprite3D",
											"props":{
												"isStatic":false,
												"name":"jingubang"
											},
											"customProps":{
												"layer":0,
												"translate":[
													0,
													0,
													0
												],
												"rotation":[
													0,
													0.7071068,
													0,
													-0.7071068
												],
												"scale":[
													1,
													1,
													1
												],
												"meshPath":"Assets/1001/Art/Models/Hero/hero03/jingubang-jingubang.lm",
												"materials":[
													{
														"type":"Laya.BlinnPhongMaterial",
														"path":"Assets/1001/Art/Models/Hero/hero03/Materials/gendouyun.lmat"
													}
												]
											},
											"components":{},
											"child":[]
										}
									]
								},
								{
									"type":"SkinnedMeshSprite3D",
									"props":{
										"isStatic":false,
										"name":"hero_dt03"
									},
									"customProps":{
										"layer":0,
										"translate":[
											0,
											0,
											0
										],
										"rotation":[
											0.7071068,
											0,
											0,
											-0.7071067
										],
										"scale":[
											1,
											1,
											1
										],
										"rootBone":"Bip001 Pelvis",
										"boundBox":{
											"min":[
												-0.9456015,
												-0.4337988,
												-0.8086619
											],
											"max":[
												1.760035,
												0.4027459,
												0.80866
											]
										},
										"boundSphere":{
											"center":[
												0.4072167,
												-0.01552644,
												-9.23872E-07
											],
											"radius":1.630645
										},
										"materials":[
											{
												"type":"Laya.BlinnPhongMaterial",
												"path":"Assets/1001/Art/Models/Hero/hero03/Materials/hero_dt03.lmat"
											}
										],
										"meshPath":"Assets/1001/Art/Models/Hero/hero03/hero03_action-hero_dt03.lm"
									},
									"components":{},
									"child":[]
								}
							]
						}
					]
				}
			]
		}
	]
}
