{
	"type":"Scene",
	"props":{
		"name":"Hero_02",
		"enableFog":false,
		"fogStart":0,
		"fogRange":300
	},
	"customProps":{
		"skyBox":{},
		"lightmaps":[],
		"ambientColor":[
			0.212,
			0.227,
			0.259
		],
		"fogColor":[
			0.5,
			0.5,
			0.5
		]
	},
	"child":[
		{
			"type":"Sprite3D",
			"props":{
				"isStatic":false,
				"name":"Hero_02"
			},
			"customProps":{
				"layer":9,
				"translate":[
					4.83,
					-0.06,
					0
				],
				"rotation":[
					0,
					0,
					0,
					-1
				],
				"scale":[
					1,
					1,
					1
				]
			},
			"components":{
				"BoxCollider":{
					"isTrigger":false,
					"center":[
						0,
						1.11599,
						0
					],
					"size":[
						1,
						2.226691,
						1
					]
				},
				"Rigidbody":{}
			},
			"child":[
				{
					"type":"Sprite3D",
					"props":{
						"isStatic":false,
						"name":"Offset"
					},
					"customProps":{
						"layer":0,
						"translate":[
							0,
							0,
							0
						],
						"rotation":[
							0,
							0,
							0,
							-1
						],
						"scale":[
							1,
							1,
							1
						]
					},
					"components":{},
					"child":[
						{
							"type":"Sprite3D",
							"props":{
								"isStatic":false,
								"name":"hero02_action"
							},
							"customProps":{
								"layer":0,
								"translate":[
									0,
									0,
									0
								],
								"rotation":[
									0,
									0,
									0,
									-1
								],
								"scale":[
									1,
									1,
									1
								]
							},
							"components":{
								"Animator":{
									"avatar":{
										"path":"Assets/1001/Art/Models/Hero/hero02/hero02_action-hero02_action-hero02_actionAvatar.lav",
										"linkSprites":{
											"Bone006":[
												"Bone006"
											],
											"Bip001 Spine1":[
												"Bip001 Spine1"
											]
										}
									},
									"clipPaths":[
										"Assets/1001/Art/Models/Hero/hero02/hero02_admin01-hero_run.lani",
										"Assets/1001/Art/Models/Hero/hero02/hero02_admin01-hero_run_left.lani",
										"Assets/1001/Art/Models/Hero/hero02/hero02_admin01-hero_run_right.lani",
										"Assets/1001/Art/Models/Hero/hero02/hero02_admin01-hero_shovel.lani",
										"Assets/1001/Art/Models/Hero/hero02/hero02_admin01-hero_jump.lani",
										"Assets/1001/Art/Models/Hero/hero02/hero02_admin01-hero_jump_setdown.lani",
										"Assets/1001/Art/Models/Hero/hero02/hero02_admin01-hero_down.lani",
										"Assets/1001/Art/Models/Hero/hero02/hero02_admin01-hero_stagger_l.lani",
										"Assets/1001/Art/Models/Hero/hero02/hero02_admin01-hero_stagger_r.lani",
										"Assets/1001/Art/Models/Hero/hero02/hero02_admin01-hero_lost1_01.lani",
										"Assets/1001/Art/Models/Hero/hero02/hero02_admin01-hero_jump_hello.lani",
										"Assets/1001/Art/Models/Hero/hero02/hero02_admin01-hero_jump_roll1.lani",
										"Assets/1001/Art/Models/Hero/hero02/hero02_admin01-hero_jump_roll2.lani",
										"Assets/1001/Art/Models/Hero/hero02/hero02_admin01-hero_jump_left.lani",
										"Assets/1001/Art/Models/Hero/hero02/hero02_admin01-hero_jump_right.lani",
										"Assets/1001/Art/Models/Hero/hero02/hero02_admin01-hero_flay.lani",
										"Assets/1001/Art/Models/Hero/hero02/hero02_admin01-hero_flay_fall.lani",
										"Assets/1001/Art/Models/Hero/hero02/hero02_admin02-hero_skate_down.lani",
										"Assets/1001/Art/Models/Hero/hero02/hero02_admin02-hero_skate_jump.lani",
										"Assets/1001/Art/Models/Hero/hero02/hero02_admin02-hero_skate_jump01.lani",
										"Assets/1001/Art/Models/Hero/hero02/hero02_admin02-hero_skate_jump02.lani",
										"Assets/1001/Art/Models/Hero/hero02/hero02_admin02-hero_skate_jump03.lani",
										"Assets/1001/Art/Models/Hero/hero02/hero02_admin02-hero_skate_left.lani",
										"Assets/1001/Art/Models/Hero/hero02/hero02_admin02-hero_skate_right.lani",
										"Assets/1001/Art/Models/Hero/hero02/hero02_admin02-hero_skate_run.lani",
										"Assets/1001/Art/Models/Hero/hero02/hero02_admin02-hero_skate_shovel.lani",
										"Assets/1001/Art/Models/Hero/hero02/hero02_admin02-hero_skate_skidding.lani",
										"Assets/1001/Art/Models/Hero/hero01/hero01_admin02-hero_skate_setdown.lani",
										"Assets/1001/Art/Models/Hero/hero02/hero02_admin02-hero_skate_jump04.lani",
										"Assets/1001/Art/Models/Hero/hero02/hero02_admin02-hero_skate_up_skb.lani",
										"Assets/1001/Art/Models/Hero/hero02/hero02_admin02-hero_skate_jump05.lani"
									],
									"playOnWake":true
								}
							},
							"child":[
								{
									"type":"Sprite3D",
									"props":{
										"isStatic":false,
										"name":"Bone006"
									},
									"customProps":{
										"layer":0,
										"translate":[
											0.06161642,
											-0.01683504,
											0.1347548
										],
										"rotation":[
											5.764203E-06,
											-8.381259E-08,
											0.0103901,
											-0.999946
										],
										"scale":[
											1.000001,
											1.000001,
											1
										]
									},
									"components":{},
									"child":[
										{
											"type":"MeshSprite3D",
											"props":{
												"isStatic":false,
												"name":"huaban"
											},
											"customProps":{
												"layer":0,
												"translate":[
													0.01,
													-0.41,
													-0.116
												],
												"rotation":[
													-3.72529E-09,
													2.235174E-08,
													4.93601E-08,
													-1
												],
												"scale":[
													0.1,
													0.1,
													0.1
												],
												"meshPath":"Assets/1001/Art/Models/Hero/huaban/huaban-huaban.lm",
												"materials":[
													{
														"type":"Laya.BlinnPhongMaterial",
														"path":"Assets/1001/Art/Models/Hero/huaban/Materials/huaban.lmat"
													}
												]
											},
											"components":{},
											"child":[]
										}
									]
								},
								{
									"type":"Sprite3D",
									"props":{
										"isStatic":false,
										"name":"Bip001 Spine1"
									},
									"customProps":{
										"layer":0,
										"translate":[
											4.768372E-07,
											1.2384,
											0.05553338
										],
										"rotation":[
											-0.4718258,
											-0.5266685,
											-0.4718258,
											-0.5266697
										],
										"scale":[
											1,
											1,
											1
										]
									},
									"components":{},
									"child":[
										{
											"type":"MeshSprite3D",
											"props":{
												"isStatic":false,
												"name":"BonePoint"
											},
											"customProps":{
												"layer":0,
												"translate":[
													0.177,
													-0.407,
													0
												],
												"rotation":[
													0,
													0,
													0,
													-1
												],
												"scale":[
													0.65,
													0.65,
													0.65
												],
												"meshPath":"Assets/1001/Art/Models/LayaPlane/Plane-Plane.lm",
												"materials":[
													{
														"type":"Laya.BlinnPhongMaterial",
														"path":"Assets/1001/Art/Models/Hero/hero02/Materials/hero_dt02.lmat"
													}
												]
											},
											"components":{
												"BoxCollider":{
													"isTrigger":false,
													"center":[
														0,
														0,
														0
													],
													"size":[
														1,
														1,
														1
													]
												}
											},
											"child":[]
										}
									]
								},
								{
									"type":"SkinnedMeshSprite3D",
									"props":{
										"isStatic":false,
										"name":"hero_dt02"
									},
									"customProps":{
										"layer":0,
										"translate":[
											0,
											0,
											-8.503956E-09
										],
										"rotation":[
											0.7071068,
											0,
											0,
											-0.7071067
										],
										"scale":[
											1,
											1,
											1
										],
										"rootBone":"Bip001 Pelvis",
										"boundBox":{
											"min":[
												-0.9414735,
												-1.088996,
												-0.8980719
											],
											"max":[
												1.848762,
												0.3164603,
												0.6997602
											]
										},
										"boundSphere":{
											"center":[
												0.4536442,
												-0.3862677,
												-0.09915584
											],
											"radius":1.75455
										},
										"materials":[
											{
												"type":"Laya.BlinnPhongMaterial",
												"path":"Assets/1001/Art/Models/Hero/hero02/Materials/hero_dt02.lmat"
											}
										],
										"meshPath":"Assets/1001/Art/Models/Hero/hero02/hero02_action-hero_dt02.lm"
									},
									"components":{},
									"child":[]
								}
							]
						}
					]
				}
			]
		}
	]
}
